apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rsync.fullname" . }}-config
  labels:
    {{- include "rsync.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configs }}
  {{ $key }}: |
{{ $val | indent 4 }}
  {{- end }}
