apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsync.fullname" . }}
  labels:
    {{- include "rsync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "rsync.selectorLabels" . | nindent 4 }}