[package]
name = "apiserver"
edition.workspace = true
version.workspace = true

[dependencies]
util = { path = "../common/util" }
core = { path = "../common/core" }
config = { path = "../common/config" }
pic_recog = { path = "../pic_recog" }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
tower = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
toml = { workspace = true }
rand = { workspace = true }
