[package]
name = "rsync"
version = "0.1.0"
edition = "2021"

[dependencies]
rule = { path = "lib/rule" }
tokio = { version = "1.0", features = ["full"] }

[workspace]
members = ["lib/core", "lib/rule"]

[[bin]]
name = "rsync"
path = "src/main.rs"
