[package]
name = "rc"
version.workspace = true
edition.workspace = true

[dependencies]
util = { path = "../common/util" }
core = { path = "../common/core" }
clap.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
